version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: alertflow_postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: alertflow
        ports:
            - '5432:5432'

    redis:
        image: redis:7
        container_name: alertflow_redis
        restart: always
        ports:
            - '6379:6379'
